// Code generated by oto; DO NOT EDIT.

'use strict';

 
export class Healthcheck {
	
	/**
	* @param {string} url URL of kite backend. Can be left blank.
	* @param healthcheckRequest github.com/aevea/knit/api/definitions.HealthcheckRequest
	*/
	async check(url, healthcheckRequest) {
		const headers = {
			'Accept':		'application/json',
			'Accept-Encoding':	'gzip',
			'Content-Type':		'application/json',
		}
		healthcheckRequest = healthcheckRequest || {}
		const response = await fetch(`${url}/oto/Healthcheck.Check`, {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(healthcheckRequest)
		})
		return response.json().then((json) => {
			if (json.error) {
				throw new Error(json.error)
			}
			return json
		})
	}
	
}
 
export class PullRequestService {
	
	/**
	* @param {string} url URL of kite backend. Can be left blank.
	* @param oldestRequest github.com/aevea/knit/api/definitions.OldestRequest
	*/
	async oldest(url, oldestRequest) {
		const headers = {
			'Accept':		'application/json',
			'Accept-Encoding':	'gzip',
			'Content-Type':		'application/json',
		}
		oldestRequest = oldestRequest || {}
		const response = await fetch(`${url}/oto/PullRequestService.Oldest`, {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(oldestRequest)
		})
		return response.json().then((json) => {
			if (json.error) {
				throw new Error(json.error)
			}
			return json
		})
	}
	
}
