name: Publish Client

on:
  push:
    branches:
      - master
    paths:
      - "/api/definitions/**"
    tags:
      - "v*"

jobs:
  publish:
    name: "Publish Client"
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go install github.com/magefile/mage
          mage install
          mage publishclient
